name: Documentation

on:
  push:
  pull_request:
    
permissions:
    contents: write
    pages: write
    pull-requests: write
jobs:
  doc-generated-check:
    name: Check documentation has been generated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/dev_requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -r requirements.txt
          pip install --upgrade --upgrade-strategy eager -r dev_requirements.txt
          pip install .[tests]
      
      - name: Check if documentation has been generated
        run: |
          make create-api-docs
          if [ $(git status -s | wc -l) -gt 0 ]; then echo "Need to run 'make create-api-docs' to generate the new API documentation and commit the documentation to the repository."; exit 1; fi

  doc-build-check:
    name: Check documentation can build
    runs-on: ubuntu-latest
    needs: doc-generated-check
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Node JS
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ./docs/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./docs/yarn.lock') }}
          restore-keys: ${{ runner.os }}-
      - name: Test Build
        run: |
          cd ./docs
          yarn install
          yarn build


  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          cd ./docs
          yarn install
      - name: Build website
        run: |
          cd ./docs
          yarn build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./docs/build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com          
