name: Publishing Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  release-build:
    if: github.repository == 'UCREL/pymusas'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.02

      - name: Set up Python 3.13
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2
        id: python-setup
        with:
          python-version: 3.13
      
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        id: setup-uv
        with:
          # Install a specific version of uv.
          version: "0.11.8"
          enable-cache: false
          restore-cache: false
          save-cache: false
          python-version: 3.13

      - name: Build release distributions
        run: |
          uv build

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
